language: node__js
node__js:
  - "v12.9.1"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai'
install:
  - npm install
script:
  # - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  target-branch: gh-pages
  verbose: true
  on:
    branch: master
